swagger: '2.0'
info:
  description: "KomMonitor Client config file storage server API, which can store and serve various config files for Kommonitor client(s)."
  version: "0.0.1"
  title: "KomMonitor Client Config Storage Server API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "christian.danowski-buhren@hs-bochum.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8088"
basePath: "/config"
tags:
- name: "web-client app config"
  description: "Config for Web Client application configuration"
- name: "web-client keycloak config"
  description: "Config for Web Client Keycloak configuration"  
- name: "web-client controls config"
  description: "Config for Web Client controls configuration"  
schemes:
- "http"
- "https"
securityDefinitions:
  # basicAuth: abcdef12345
   basicAuth:
     type: basic

security:
  - basicAuth: []

paths:

  /client-app-config:
      post:
        tags:
        - "web-client app config"
        summary: "Send web app client config to be stored on server."
        description: "Send web app client config to be stored on server."
        operationId: "postWebAppConfig"
        consumes:
         - multipart/form-data
        parameters:
         - in: formData
           name: appConfig
           type: file
           description: The file to upload as javascript file.
        responses:
          200:
            description: "OK"
          500:
            description: "Error"
      get:
        tags:
          - "web-client app config"
        summary: "retrieve web app client config."
        description: "retrieve web app client config."
        operationId: "getWebAppConfig"
        produces:
          - application/javascript
        responses:
          200:
            description: The web app config file as JavaScript file.
            schema:
              type: file  
              
  /client-keycloak-config:
      post:
        tags:
        - "web-client keycloak config"
        summary: "Send web app client keycloak config to be stored on server."
        description: "Send web app client keycloak config to be stored on server."
        operationId: "postWebAppKeycloakConfig"
        consumes:
         - multipart/form-data
        parameters:
         - in: formData
           name: appConfig
           type: file
           description: The file to upload as JSON file.
        responses:
          200:
            description: "OK"
          500:
            description: "Error"
      get:
        tags:
          - "web-client keycloak config"
        summary: "retrieve web app client keycloak config."
        description: "retrieve web app client keycloak config."
        operationId: "getWebAppKeycloakConfig"
        produces:
          - application/json
        responses:
          200:
            description: The web app keycloak config file as JSON file.
            schema:
              type: file  
              
  /client-controls-config:
      post:
        tags:
        - "web-client controls config"
        summary: "Send web app client controls config to be stored on server."
        description: "Send web app client controls config to be stored on server."
        operationId: "postWebAppControlsConfig"
        consumes:
         - multipart/form-data
        parameters:
         - in: formData
           name: appConfig
           type: file
           description: The file to upload as JSON file.
        responses:
          200:
            description: "OK"
          500:
            description: "Error"
      get:
        tags:
          - "web-client controls config"
        summary: "retrieve web app client controls config."
        description: "retrieve web app client controls config."
        operationId: "getWebAppControlsConfig"
        produces:
          - application/json
        responses:
          200:
            description: The web app controls config file as JSON file.
            schema:
              type: file                


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
